### ISSUE TITLE
Need help building the plugin on XCode

### ISSUE THREAD

**Issue by ivanhalen6** [Computer-Assisted-Clinical-Medicine/UMMPerfusion#1]
Hi! I really need to use this plugin and I can´t figure out why it just won´t build anymore. I see there were recent changes, is it not available anymore? 
The current issue I´m having right now is ´Unknown type name 'ToolMode' ´, even though I did find ´ToolMode currentTool, currentToolRight, currentMouseEventTool;´ in DCMView.h . Also, a lot of headers appear as missing, and I have to rebuild them in Visual Studio Code and then add the specific created files to the project. Sometimes, it does not fix it anyway...
I´m pretty new to programming, so sorry about that. But I really wish I could try this plugin.
Thanks!

**Comment by fzoellne** [comment]
Please have a lookout the recent update of the source code. Should fix some issues.

**Comment by ivanhalen6** [comment]
Thanks! Successfully built it. Got an error, corrected this:

The bundle “PluginTemplate” couldn’t be loaded because it doesn’t contain a version for the current architecture.

dlopen_preflight(/Library/Application Support/OsiriX/Plugins/UMMPerfusion.osirixplugin/Contents/MacOS/UMMPerfusion) => false, tried: '/Library/Application Support/OsiriX/Plugins/UMMPerfusion.osirixplugin/Contents/MacOS/UMMPerfusion' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Application Support/OsiriX/Plugins/UMMPerfusion.osirixplugin/Contents/MacOS/UMMPerfusion' (no such file), '/Library/Application Support/OsiriX/Plugins/UMMPerfusion.osirixplugin/Contents/MacOS/UMMPerfusion' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

But now after installing it on Osirix Lite, I´m getting 

“The bundle “PluginTemplate” couldn’t be loaded.

dlopen(/Library/Application Support/OsiriX/Plugins/UMMPerfusion.osirixplugin/Contents/MacOS/UMMPerfusion, 0x0109): symbol not found in flat namespace '_GRAxesDrawXLabels' ”

And it does not load on Horos. I´ll try Miele next as well...

**Comment by ivanhalen6** [comment]
Hi, sorry to bother you again. But I still can´t get it to work, the same problem showing on the plugins list... 
“The bundle “PluginTemplate” couldn’t be loaded.

dlopen(/Library/Application Support/OsiriX/Plugins/UMMPerfusion.osirixplugin/Contents/MacOS/UMMPerfusion, 0x0109): symbol not found in flat namespace '_GRAxesDrawXLabels' ”

Can you help me out again? Should I open another issue fot that?
